const initApi = require('./api');
const filteredTracks = require('./filtered.json');

const tracks = filteredTracks.sort((a, b) => b.tempo - a.tempo);

const zeroPad = number => (
  number < 10 ? `0${number}` : number
);

module.exports = (auth) => {
  const { get, post, postAll } = initApi(auth);

  return get('/me')
    .then((user) => {
      const today = new Date();
      const formattedDate = `${today.getFullYear()}-${zeroPad(today.getMonth() + 1)}-${zeroPad(today.getDate())}`;
      const playlist = {
        name: `Running ${formattedDate}`,
        description: `Auto-playlist of songs for running. Generated by github.com/camjackson/spotify/automation on ${formattedDate}`,
      };

      console.log('-------------');
      console.log(`Retrieved user ${user.id}`);
      console.log(`Creating a new playlist called "${playlist.name}"`);

      return post(`/users/${user.id}/playlists`, playlist)
        .then(newPlaylist => [newPlaylist, user]);
    }).then(([playlist, user]) => {
      console.log('Playlist created succesfully!');
      console.log('-------------\n');

      console.log('-------------');
      console.log(`Adding ${tracks.length} tracks to the playlist...`);

      const trackUriSets = [];
      const numberOfTrackAddRequests = Math.ceil(tracks.length / 100);
      for (let i = 0; i < numberOfTrackAddRequests; i++) {
        const trackUris = tracks.slice(i * 100, (i + 1) * 100).map(track => track.uri);
        trackUriSets.push(trackUris);
      }
      return postAll(`/users/${user.id}/playlists/${playlist.id}/tracks`, trackUriSets)
        .then(() => [playlist, user]);
    }).then(([playlist, user]) => {
      console.log('Tracks added succesfully succesfully!');
      return get(`/users/${user.id}/playlists/${playlist.id}`);
    })
    .then((playlist) => {
      console.log(`Playlist now has ${playlist.tracks.total} tracks!`);
      console.log('-------------\n');
    });
};
