const allArtists = [
  'Skyharbor',
  'SBTRKT',
  'The Presets',
  'TesseracT',
  'Voices from the Fuselage',
  'Thrice',
  'Disturbed',
  'Incubus',
  'The Occupants',
  'Hiatus Kaiyote',
  'Face To Face',
  'Alexisonfire',
  'The Offspring',
  'Porcupine Tree',
  'System Of A Down',
  'Periphery',
  'Killing Heidi',
  'Cog',
  'Karnivool',
  'Snarky Puppy',
  'Solar Fields',
  'Pendulum',
];
